# fly.toml file generated for sshpiper on 2023-02-27T16:05:23Z

app = "sshpiper"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  SSHPIPERD_GITHUBAPP_BASEURL="https://sshpiper.com"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 2222
  protocol = "tcp"

  [[services.ports]]
    port = "22"
    handlers = ["proxy_proto"]


[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 250
    soft_limit = 200
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
